/*
This file contains country names and codes

RESTRICTIONS:
	- Do not edit this comment section.

NOTES:
    To improve code readability, the constant names do not follow camelCase.
	Do not remove IDE inspection directives

COPYRIGHT and WARRANTY:
	Copyright 2022
	Licensed under the Apache License, Version 2.0 (the "License");
	you may not use this file except in compliance with the License.
	You may obtain a copy of the License at

	http://www.apache.org/licenses/LICENSE-2.0

	Unless required by applicable law or agreed to in writing, software
	distributed under the License is distributed on an "AS IS" BASIS,
	WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
	See the License for the specific language governing permissions and
	limitations under the License.

*/
library reusable_const_vars;

const bashColors = {
  'BASH_COLOR_RESET': '\x1B[0m',
  'BASH_COLOR_RED': '\x1B[31m',
  'BASH_COLOR_GREEN': '\x1B[32m',
  'BASH_COLOR_YELLOW': '\x1B[33m',
  'BASH_COLOR_BLUE': '\x1B[34m',
  'BASH_COLOR_PURPLE': '\x1B[35m',
  'BASH_COLOR_CYAN': '\x1B[36m',
  'BASH_COLOR_WHITE': '\x1B[37m',
};

const WEBSAFE_ALICE_BLUE = "#F0F8FF";
const WEBSAFE_ANTIQUE_WHITE = "#FAEBD7";
const WEBSAFE_AQUA = "#00FFFF";
const WEBSAFE_AQUA_MARINE = "#7FFFD4";
const WEBSAFE_AZURE = "#F0FFFF";
const WEBSAFE_BEIGE = "#F5F5DC";
const WEBSAFE_BISQUE = "#FFE4C4";
const WEBSAFE_BLACK = "#000000";
const WEBSAFE_BLANCHED_ALMOND = "#FFEBCD";
const WEBSAFE_BLUE = "#0000FF";
const WEBSAFE_BLUE_VIOLET = "#8A2BE2";
const WEBSAFE_BROWN = "#A52A2A";
const WEBSAFE_BURLY_WOOD = "#DEB887";
const WEBSAFE_CADET_BLUE = "#5F9EA0";
const WEBSAFE_CHART_REUSE = "#7FFF00";
const WEBSAFE_CHOCOLATE = "#D2691E";
const WEBSAFE_CORAL = "#FF7F50";
const WEBSAFE_CORN_FLOWER_BLUE = "#6495ED";
const WEBSAFE_CORN_SILK = "#FFF8DC";
const WEBSAFE_CRIMSON = "#DC143C";
const WEBSAFE_CYAN = "#00FFFF";
const WEBSAFE_DARK_BLUE = "#00008B";
const WEBSAFE_DARK_CYAN = "#008B8B";
const WEBSAFE_DARK_GOLDEN_ROD = "#B8860B";
const WEBSAFE_DARK_GRAY = "#A9A9A9";
const WEBSAFE_DARK_GREEN = "#006400";
const WEBSAFE_DARK_KHAKI = "#BDB76B";
const WEBSAFE_DARK_MAGENTA = "#8B008B";
const WEBSAFE_DARK_OLIVE_GREEN = "#556B2F";
const WEBSAFE_DARK_ORANGE = "#FF8C00";
const WEBSAFE_DARK_ORCHID = "#9932CC";
const WEBSAFE_DARK_RED = "#8B0000";
const WEBSAFE_DARK_SALMON = "#E9967A";
const WEBSAFE_DARK_SEA_GREEN = "#8FBC8F";
const WEBSAFE_DARK_SLATE_BLUE = "#483D8B";
const WEBSAFE_DARK_SLATE_GRAY = "#2F4F4F";
const WEBSAFE_DARK_TURQUOISE = "#00CED1";
const WEBSAFE_DARK_VIOLET = "#9400D3";
const WEBSAFE_DEEP_PINK = "#FF1493";
const WEBSAFE_DEEP_SKY_BLUE = "#00BFFF";
const WEBSAFE_DIMG_RAY = "#696969";
const WEBSAFE_DODGER_BLUE = "#1E90FF";
const WEBSAFE_FIRE_BRICK = "#B22222";
const WEBSAFE_FLORAL_WHITE = "#FFFAF0";
const WEBSAFE_FOREST_GREEN = "#228B22";
const WEBSAFE_FUCHSIA = "#FF00FF";
const WEBSAFE_GAINSBORO = "#DCDCDC";
const WEBSAFE_GHOST_WHITE = "#F8F8FF";
const WEBSAFE_GOLD = "#FFD700";
const WEBSAFE_GOLDEN_ROD = "#DAA520";
const WEBSAFE_GRAY = "#808080";
const WEBSAFE_GREEN = "#008000";
const WEBSAFE_GREEN_YELLOW = "#ADFF2F";
const WEBSAFE_HONEY_DEW = "#F0FFF0";
const WEBSAFE_HOT_PINK = "#FF69B4";
const WEBSAFE_INDIAN_RED = "#CD5C5C";
const WEBSAFE_INDIGO = "#4B0082";
const WEBSAFE_IVORY = "#FFFFF0";
const WEBSAFE_KHAKI = "#F0E68C";
const WEBSAFE_LAVENDER = "#E6E6FA";
const WEBSAFE_LAVENDER_BLUSH = "#FFF0F5";
const WEBSAFE_LAWN_GREEN = "#7CFC00";
const WEBSAFE_LEMON_CHIFFON = "#FFFACD";
const WEBSAFE_LIGHT_BLUE = "#ADD8E6";
const WEBSAFE_LIGHT_CORAL = "#F08080";
const WEBSAFE_LIGHT_CYAN = "#E0FFFF";
const WEBSAFE_LIGHT_GOLDEN_ROD_YELLOW = "#FAFAD2";
const WEBSAFE_LIGHT_GRAY = "#D3D3D3";
const WEBSAFE_LIGHT_GREEN = "#90EE90";
const WEBSAFE_LIGHT_PINK = "#FFB6C1";
const WEBSAFE_LIGHT_SALMON = "#FFA07A";
const WEBSAFE_LIGHT_SEA_GREEN = "#20B2AA";
const WEBSAFE_LIGHT_SKY_BLUE = "#87CEFA";
const WEBSAFE_LIGHT_SLATE_GRAY = "#778899";
const WEBSAFE_LIGHT_STEEL_BLUE = "#B0C4DE";
const WEBSAFE_LIME = "#00FF00";
const WEBSAFE_LIME_GREEN = "#32CD32";
const WEBSAFE_LINEN = "#FAF0E6";
const WEBSAFE_MAROON = "#800000";
const WEBSAFE_MEDIUM_AQUAMARINE = "#66CDAA";
const WEBSAFE_MEDIUM_BLUE = "#0000CD";
const WEBSAFE_MEDIUM_ORCHID = "#BA55D3";
const WEBSAFE_MEDIUM_PURPLE = "#9370DB";
const WEBSAFE_MEDIUM_SEA_GREEN = "#3CB371";
const WEBSAFE_MEDIUM_SLATE_BLUE = "#7B68EE";
const WEBSAFE_MEDIUM_SPRING_GREEN = "#00FA9A";
const WEBSAFE_MEDIUM_TURQUOISE = "#48D1CC";
const WEBSAFE_MEDIUM_VIOLET_RED = "#C71585";
const WEBSAFE_MIDNIGHT_BLUE = "#191970";
const WEBSAFE_MINT_CREAM = "#F5FFFA";
const WEBSAFE_MISTY_ROSE = "#FFE4E1";
const WEBSAFE_MOCCASIN = "#FFE4B5";
const WEBSAFE_NAVAJO_WHITE = "#FFDEAD";
const WEBSAFE_NAVY = "#000080";
const WEBSAFE_OLD_LACE = "#FDF5E6";
const WEBSAFE_OLIVE = "#808000";
const WEBSAFE_OLIVE_DRAB = "#6B8E23";
const WEBSAFE_ORANGE = "#FFA500";
const WEBSAFE_ORANGE_RED = "#FF4500";
const WEBSAFE_ORCHID = "#DA70D6";
const WEBSAFE_PALE_GOLDEN_ROD = "#EEE8AA";
const WEBSAFE_PALE_GREEN = "#98FB98";
const WEBSAFE_PALE_TURQUOISE = "#AFEEEE";
const WEBSAFE_PALE_VIOLETRED = "#DB7093";
const WEBSAFE_PAPAYA_WHIP = "#FFEFD5";
const WEBSAFE_PEACH_PUFF = "#FFDAB9";
const WEBSAFE_PERU = "#CD853F";
const WEBSAFE_PINK = "#FFC0CB";
const WEBSAFE_PLUM = "#DDA0DD";
const WEBSAFE_POWDER_BLUE = "#B0E0E6";
const WEBSAFE_PURPLE = "#800080";
const WEBSAFE_QUARTZ = "#54FF9F";
const WEBSAFE_RED = "#FF0000";
const WEBSAFE_ROSY_BROWN = "#BC8F8F";
const WEBSAFE_ROYAL_BLUE = "#4169E1";
const WEBSAFE_SADDLE_BROWN = "#8B4513";
const WEBSAFE_SALMON = "#FA8072";
const WEBSAFE_SANDY_BROWN = "#F4A460";
const WEBSAFE_SEA_GREEN = "#2E8B57";
const WEBSAFE_SIENNA = "#A0522D";
const WEBSAFE_SILVER = "#C0C0C0";
const WEBSAFE_SKY_BLUE = "#87CEEB";
const WEBSAFE_SLATE_BLUE = "#6A5ACD";
const WEBSAFE_SLATE_GRAY = "#778899";
const WEBSAFE_STEEL_BLUE = "#4682B4";
const WEBSAFE_TEAL = "#008080";
const WEBSAFE_TOMATO = "#FF6347";
const WEBSAFE_TURQUOISE = "#40E0D0";
const WEBSAFE_VIOLET = "#EE82EE";
const WEBSAFE_WHEAT = "#F5DEB3";
const WEBSAFE_WHITE = "#FFFFFF";
const WEBSAFE_WHITE_SMOKE = "#F5F5F5";
const WEBSAFE_YELLOW = "#FFFF00";
const WEBSAFE_YELLOW_GREEN = "#9ACD32";
const WEBSAFE_ZAPIER = "#29B6F6";
