/*
This file contains country names and codes

RESTRICTIONS:
	- Do not edit this comment section.

NOTES:
    To improve code readability, the constant names do not follow camelCase.
	Do not remove IDE inspection directives

COPYRIGHT and WARRANTY:
	Copyright 2022
	Licensed under the Apache License, Version 2.0 (the "License");
	you may not use this file except in compliance with the License.
	You may obtain a copy of the License at

	http://www.apache.org/licenses/LICENSE-2.0

	Unless required by applicable law or agreed to in writing, software
	distributed under the License is distributed on an "AS IS" BASIS,
	WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
	See the License for the specific language governing permissions and
	limitations under the License.

*/
library reusable_const_vars;

const Map<String, String> countryCodes = {
  "AFG": "Afghanistan",
  "ALA": "Åland Islands",
  "ALB": "Albania",
  "DZA": "Algeria",
  "ASM": "American Samoa",
  "AND": "Andorra",
  "AGO": "Angola",
  "AIA": "Anguilla",
  "ATA": "Antarctica",
  "ATG": "Antigua and Barbuda",
  "ARG": "Argentina",
  "ARM": "Armenia",
  "ABW": "Aruba",
  "AUS": "Australia",
  "AUT": "Austria",
  "AZE": "Azerbaijan",
  "BHS": "Bahamas, the",
  "BHR": "Bahrain",
  "BGD": "Bangladesh",
  "BRB": "Barbados",
  "BLR": "Belarus",
  "BEL": "Belgium",
  "BLZ": "Belize",
  "BEN": "Benin",
  "BMU": "Bermuda",
  "BTN": "Bhutan",
  "BOL": "Bolivia (Plurinational State of)",
  "BES": "Bonaire, Sint Eustatius and Saba",
  "BIH": "Bosnia and Herzegovina",
  "BWA": "Botswana",
  "BVT": "Bouvet Island",
  "BRA": "Brazil",
  "IOT": "British Indian Ocean Territory (the)",
  "BRN": "Brunei Darussalam",
  "BGR": "Bulgaria",
  "BFA": "Burkina Faso",
  "BDI": "Burundi",
  "CPV": "Cabo Verde",
  "KHM": "Cambodia",
  "CMR": "Cameroon",
  "CAN": "Canada",
  "CYM": "Cayman Islands (the)",
  "CAF": "Central African Republic (the)",
  "TCD": "Chad",
  "CHL": "Chile",
  "CHN": "China",
  "CXR": "Christmas Island",
  "CCK": "Cocos (Keeling) Islands (the)",
  "COL": "Colombia",
  "COM": "Comoros (the)",
  "COD": "Congo (the Democratic Republic of the)",
  "COG": "Congo (the)",
  "COK": "Cook Islands (the)",
  "CRI": "Costa Rica",
  "CIV": "Côte d'Ivoire",
  "HRV": "Croatia",
  "CUB": "Cuba",
  "CUW": "Curaçao",
  "CYP": "Cyprus",
  "CZE": "Czechia",
  "DNK": "Denmark",
  "DJI": "Djibouti",
  "DMA": "Dominica",
  "DOM": "Dominican Republic (the)",
  "ECU": "Ecuador",
  "EGY": "Egypt",
  "SLV": "El Salvador",
  "GNQ": "Equatorial Guinea",
  "ERI": "Eritrea",
  "EST": "Estonia",
  "SWZ": "Eswatini",
  "ETH": "Ethiopia",
  "FLK": "Falkland Islands (the) [Malvinas]",
  "FRO": "Faroe Islands (the)",
  "FJI": "Fiji",
  "FIN": "Finland",
  "FRA": "France",
  "GUF": "French Guiana",
  "PYF": "French Polynesia",
  "ATF": "French Southern Territories (the)",
  "GAB": "Gabon",
  "GMB": "Gambia (the)",
  "GEO": "Georgia",
  "DEU": "Germany",
  "GHA": "Ghana",
  "GIB": "Gibraltar",
  "GRC": "Greece",
  "GRL": "Greenland",
  "GRD": "Grenada",
  "GLP": "Guadeloupe",
  "GUM": "Guam",
  "GTM": "Guatemala",
  "GGY": "Guernsey",
  "GIN": "Guinea",
  "GNB": "Guinea_Bissau",
  "GUY": "Guyana",
  "HTI": "Haiti",
  "HMD": "Heard_Island_and_McDonald_Islands",
  "VAT": "Holy_See_the",
  "HND": "Honduras",
  "HKG": "Hong_Kong",
  "HUN": "Hungary",
  "ISL": "Iceland",
  "IND": "India",
  "IDN": "Indonesia",
  "IRN": "Iran_Islamic_Republic_of",
  "IRQ": "Iraq",
  "IRL": "Ireland",
  "IMN": "Isle_of_Man",
  "ISR": "Israel",
  "ITA": "Italy",
  "JAM": "Jamaica",
  "JPN": "Japan",
  "JEY": "Jersey",
  "JOR": "Jordan",
  "KAZ": "Kazakhstan",
  "KEN": "Kenya",
  "KIR": "Kiribati",
  "PRK": "Korea_the_Democratic_Peoples_Republic_of",
  "KOR": "Korea_the_Republic_of",
  "KWT": "Kuwait",
  "KGZ": "Kyrgyzstan",
  "LAO": "Lao_Peoples_Democratic_Republic_the",
  "LVA": "Latvia",
  "LBN": "Lebanon",
  "LSO": "Lesotho",
  "LBR": "Liberia",
  "LBY": "Libya",
  "LIE": "Liechtenstein",
  "LTU": "Lithuania",
  "LUX": "Luxembourg",
  "MAC": "Macao",
  "MDG": "Madagascar",
  "MWI": "Malawi",
  "MYS": "Malaysia",
  "MDV": "Maldives",
  "MLI": "Mali",
  "MLT": "Malta",
  "MHL": "Marshall_Islands_the",
  "MTQ": "Martinique",
  "MRT": "Mauritania",
  "MUS": "Mauritius",
  "MYT": "Mayotte",
  "MEX": "Mexico",
  "FSM": "Micronesia_Federated_States_of",
  "MDA": "Moldova_the_Republic_of",
  "MCO": "Monaco",
  "MNG": "Mongolia",
  "MNE": "Montenegro",
  "MSR": "Montserrat",
  "MAR": "Morocco",
  "MOZ": "Mozambique",
  "MMR": "Myanmar",
  "NAM": "Namibia",
  "NRU": "Nauru",
  "NPL": "Nepal",
  "NLD": "Netherlands_Kingdom_of_the",
  "NCL": "New_Caledonia",
  "NZL": "New_Zealand",
  "NIC": "Nicaragua",
  "NER": "Niger_the",
  "NGA": "Nigeria",
  "NIU": "Niue",
  "NFK": "Norfolk_Island",
  "MKD": "North_Macedonia",
  "MNP": "Northern_Mariana_Islands_the",
  "NOR": "Norway",
  "OMN": "Oman",
  "PAK": "Pakistan",
  "PLW": "Palau",
  "PSE": "Palestine_State_of",
  "PAN": "Panama",
  "PNG": "Papua_New_Guinea",
  "PRY": "Paraguay",
  "PER": "Peru",
  "PHL": "Philippines_the",
  "PCN": "Pitcairn",
  "POL": "Poland",
  "PRT": "Portugal",
  "PRI": "Puerto_Rico",
  "QAT": "Qatar",
  "REU": "Réunion",
  "ROU": "Romania",
  "RUS": "Russian_Federation_the",
  "RWA": "Rwanda",
  "BLM": "Saint_Barthélemy",
  "SHN": "Saint_Helena_Ascension_and_Tristan_da_Cunha",
  "KNA": "Saint_Kitts_and_Nevis",
  "LCA": "Saint_Lucia",
  "MAF": "Saint_Martin_French_part",
  "SPM": "Saint_Pierre_and_Miquelon",
  "VCT": "Saint_Vincent_and_the_Grenadines",
  "WSM": "Samoa",
  "SMR": "San_Marino",
  "STP": "Sao_Tome_and_Principe",
  "SAU": "Saudi_Arabia",
  "SEN": "Senegal",
  "SRB": "Serbia",
  "SYC": "Seychelles",
  "SLE": "Sierra Leone",
  "SGP": "Singapore",
  "SXM": "Sint Maarten (Dutch part)",
  "SVK": "Slovakia",
  "SVN": "Slovenia",
  "SLB": "Solomon Islands",
  "SOM": "Somalia",
  "ZAF": "South Africa",
  "SGS": "South Georgia and the South Sandwich Islands",
  "SSD": "South Sudan",
  "ESP": "Spain",
  "LKA": "Sri Lanka",
  "SDN": "Sudan (the)",
  "SUR": "Suriname",
  "SJM": "Svalbard and Jan Mayen",
  "SWE": "Sweden",
  "CHE": "Switzerland",
  "SYR": "Syrian Arab Republic (the)",
  "TWN": "Taiwan, Province of China",
  "TJK": "Tajikistan",
  "TZA": "Tanzania, the United Republic of",
  "THA": "Thailand",
  "TLS": "Timor-Leste",
  "TGO": "Togo",
  "TKL": "Tokelau",
  "TON": "Tonga",
  "TTO": "Trinidad and Tobago",
  "TUN": "Tunisia",
  "TUR": "Türkiye",
  "TKM": "Turkmenistan",
  "TCA": "Turks and Caicos Islands (the)",
  "TUV": "Tuvalu",
  "UGA": "Uganda",
  "UKR": "Ukraine",
  "ARE": "United Arab Emirates (the)",
  "GBR": "United Kingdom of Great Britain and Northern Ireland (the)",
  "UMI": "United States Minor Outlying Islands (the)",
  "USA": "United States of America (the)",
  "URY": "Uruguay",
  "UZB": "Uzbekistan",
  "VUT": "Vanuatu",
  "VEN": "Venezuela (Bolivarian Republic of)",
  "VNM": "Viet Nam",
  "VGB": "Virgin Islands (British)",
  "VIR": "Virgin Islands (U.S.)",
  "WLF": "Wallis and Futuna",
  "ESH": "Western Sahara",
  "YEM": "Yemen",
  "ZMB": "Zambia",
  "ZWE": "Zimbabwe"
};

class Iso3166Entry {
  final String englishName;
  final String alpha2;
  final String alpha3;
  final int numeric; // Dart uses int for uint64 equivalents

  const Iso3166Entry(this.englishName, this.alpha2, this.alpha3, this.numeric);

  static Map<String, Iso3166Entry> getEntries() {
    return {
      "AFG": const Iso3166Entry("Afghanistan", "AF", "AFG", 4),
      "ALA": const Iso3166Entry("Åland Islands", "AX", "ALA", 248),
      "ALB": const Iso3166Entry("Albania", "AL", "ALB", 8),
      "DZA": const Iso3166Entry("Algeria", "DZ", "DZA", 12),
      "ASM": const Iso3166Entry("American Samoa", "AS", "ASM", 16),
      "AND": const Iso3166Entry("Andorra", "AD", "AND", 20),
      "AGO": const Iso3166Entry("Angola", "AO", "AGO", 24),
      "AIA": const Iso3166Entry("Anguilla", "AI", "AIA", 660),
      "ATA": const Iso3166Entry("Antarctica", "AQ", "ATA", 10),
      "ATG": const Iso3166Entry("Antigua and Barbuda", "AG", "ATG", 28),
      "ARG": const Iso3166Entry("Argentina", "AR", "ARG", 32),
      "ARM": const Iso3166Entry("Armenia", "AM", "ARM", 51),
      "ABW": const Iso3166Entry("Aruba", "AW", "ABW", 533),
      "AUS": const Iso3166Entry("Australia", "AU", "AUS", 36),
      "AUT": const Iso3166Entry("Austria", "AT", "AUT", 40),
      "AZE": const Iso3166Entry("Azerbaijan", "AZ", "AZE", 31),
      "BHS": const Iso3166Entry("Bahamas the", "BS", "BHS", 44),
      "BHR": const Iso3166Entry("Bahrain", "BH", "BHR", 48),
      "BGD": const Iso3166Entry("Bangladesh", "BD", "BGD", 50),
      "BRB": const Iso3166Entry("Barbados", "BB", "BRB", 52),
      "BLR": const Iso3166Entry("Belarus", "BY", "BLR", 112),
      "BEL": const Iso3166Entry("Belgium", "BE", "BEL", 56),
      "BLZ": const Iso3166Entry("Belize", "BZ", "BLZ", 84),
      "BEN": const Iso3166Entry("Benin", "BJ", "BEN", 204),
      "BMU": const Iso3166Entry("Bermuda", "BM", "BMU", 60),
      "BTN": const Iso3166Entry("Bhutan", "BT", "BTN", 64),
      "BOL": const Iso3166Entry(
          "Bolivia (Plurinational State of)", "BO", "BOL", 68),
      "BES": const Iso3166Entry(
          "Bonaire, Sint Eustatius and Saba", "BQ", "BES", 535),
      "BIH": const Iso3166Entry("Bosnia and Herzegovina", "BA", "BIH", 70),
      "BWA": const Iso3166Entry("Botswana", "BW", "BWA", 72),
      "BVT": const Iso3166Entry("Bouvet Island", "BV", "BVT", 74),
      "BRA": const Iso3166Entry("Brazil", "BR", "BRA", 76),
      "IOT": const Iso3166Entry(
          "British Indian Ocean Territory the", "IO", "IOT", 86),
      "BRN": const Iso3166Entry("Brunei Darussalam", "BN", "BRN", 96),
      "BGR": const Iso3166Entry("Bulgaria", "BG", "BGR", 100),
      "BFA": const Iso3166Entry("Burkina Faso", "BF", "BFA", 854),
      "BDI": const Iso3166Entry("Burundi", "BI", "BDI", 108),
      "CPV": const Iso3166Entry("Cabo Verde", "CV", "CPV", 132),
      "KHM": const Iso3166Entry("Cambodia", "KH", "KHM", 116),
      "CMR": const Iso3166Entry("Cameroon", "CM", "CMR", 120),
      "CAN": const Iso3166Entry("Canada", "CA", "CAN", 124),
      "CYM": const Iso3166Entry("Cayman Islands the", "KY", "CYM", 136),
      "CAF":
          const Iso3166Entry("Central African Republic the", "CF", "CAF", 140),
      "TCD": const Iso3166Entry("Chad", "TD", "TCD", 148),
      "CHL": const Iso3166Entry("Chile", "CL", "CHL", 152),
      "CHN": const Iso3166Entry("China", "CN", "CHN", 156),
      "CXR": const Iso3166Entry("Christmas Island", "CX", "CXR", 162),
      "CCK":
          const Iso3166Entry("Cocos (Keeling) Islands the", "CC", "CCK", 166),
      "COL": const Iso3166Entry("Colombia", "CO", "COL", 170),
      "COM": const Iso3166Entry("Comoros the", "KM", "COM", 0),
      "COD": const Iso3166Entry(
          "Congo (the Democratic Republic of the)", "CD", "COD", 180),
      "COG": const Iso3166Entry("Congo the", "CG", "COG", 178),
      "COK": const Iso3166Entry("Cook Islands the", "CK", "COK", 184),
      "CRI": const Iso3166Entry("Costa Rica", "CR", "CRI", 188),
      "CIV": const Iso3166Entry("Côte d'Ivoire", "CI", "CIV", 384),
      "HRV": const Iso3166Entry("Croatia", "HR", "HRV", 191),
      "CUB": const Iso3166Entry("Cuba", "CU", "CUB", 192),
      "CUW": const Iso3166Entry("Curaçao", "CW", "CUW", 531),
      "CYP": const Iso3166Entry("Cyprus", "CY", "CYP", 196),
      "CZE": const Iso3166Entry("Czechia", "CZ", "CZE", 203),
      "DNK": const Iso3166Entry("Denmark", "DK", "DNK", 208),
      "DJI": const Iso3166Entry("Djibouti", "DJ", "DJI", 262),
      "DMA": const Iso3166Entry("Dominica", "DM", "DMA", 212),
      "DOM": const Iso3166Entry("Dominican Republic the", "DO", "DOM", 214),
      "ECU": const Iso3166Entry("Ecuador", "EC", "ECU", 218),
      "EGY": const Iso3166Entry("Egypt", "EG", "EGY", 818),
      "SLV": const Iso3166Entry("El Salvador", "SV", "SLV", 222),
      "GNQ": const Iso3166Entry("Equatorial Guinea", "GQ", "GNQ", 226),
      "ERI": const Iso3166Entry("Eritrea", "ER", "ERI", 232),
      "EST": const Iso3166Entry("Estonia", "EE", "EST", 233),
      "SWZ": const Iso3166Entry("Eswatini", "SZ", "SWZ", 748),
      "ETH": const Iso3166Entry("Ethiopia", "ET", "ETH", 231),
      "FLK": const Iso3166Entry(
          "Falkland Islands the [Malvinas]", "FK", "FLK", 238),
      "FRO": const Iso3166Entry("Faroe Islands the", "FO", "FRO", 234),
      "FJI": const Iso3166Entry("Fiji", "FJ", "FJI", 0),
      "FIN": const Iso3166Entry("Finland", "FI", "FIN", 246),
      "FRA": const Iso3166Entry("France", "FR", "FRA", 250),
      "GUF": const Iso3166Entry("French Guiana", "GF", "GUF", 254),
      "PYF": const Iso3166Entry("French Polynesia", "PF", "PYF", 258),
      "ATF": const Iso3166Entry(
          "French Southern Territories the", "TF", "ATF", 260),
      "GAB": const Iso3166Entry("Gabon", "GA", "GAB", 266),
      "GMB": const Iso3166Entry("Gambia the", "GM", "GMB", 270),
      "GEO": const Iso3166Entry("Georgia", "GE", "GEO", 268),
      "DEU": const Iso3166Entry("Germany", "DE", "DEU", 276),
      "GHA": const Iso3166Entry("Ghana", "GH", "GHA", 288),
      "GIB": const Iso3166Entry("Gibraltar", "GI", "GIB", 292),
      "GRC": const Iso3166Entry("Greece", "GR", "GRC", 300),
      "GRL": const Iso3166Entry("Greenland", "GL", "GRL", 304),
      "GRD": const Iso3166Entry("Grenada", "GD", "GRD", 308),
      "GLP": const Iso3166Entry("Guadeloupe", "GP", "GLP", 312),
      "GUM": const Iso3166Entry("Guam", "GU", "GUM", 316),
      "GTM": const Iso3166Entry("Guatemala", "GT", "GTM", 320),
      "GGY": const Iso3166Entry("Guernsey", "GG", "GGY", 831),
      "GIN": const Iso3166Entry("Guinea", "GN", "GIN", 324),
      "GNB": const Iso3166Entry("Guinea-Bissau", "GW", "GNB", 624),
      "GUY": const Iso3166Entry("Guyana", "GY", "GUY", 328),
      "HTI": const Iso3166Entry("Haiti", "HT", "HTI", 332),
      "HMD": const Iso3166Entry(
          "Heard Island and McDonald Islands", "HM", "HMD", 334),
      "VAT": const Iso3166Entry("Holy See the", "VA", "VAT", 336),
      "HND": const Iso3166Entry("Honduras", "HN", "HND", 0),
      "HKG": const Iso3166Entry("Hong Kong", "HK", "HKG", 344),
      "HUN": const Iso3166Entry("Hungary", "HU", "HUN", 348),
      "ISL": const Iso3166Entry("Iceland", "IS", "ISL", 352),
      "IND": const Iso3166Entry("India", "IN", "IND", 356),
      "IDN": const Iso3166Entry("Indonesia", "ID", "IDN", 360),
      "IRN": const Iso3166Entry("Iran (Islamic Republic of)", "IR", "IRN", 364),
      "IRQ": const Iso3166Entry("Iraq", "IQ", "IRQ", 368),
      "IRL": const Iso3166Entry("Ireland", "IE", "IRL", 372),
      "IMN": const Iso3166Entry("Isle of Man", "IM", "IMN", 833),
      "ISR": const Iso3166Entry("Israel", "IL", "ISR", 376),
      "ITA": const Iso3166Entry("Italy", "IT", "ITA", 380),
      "JAM": const Iso3166Entry("Jamaica", "JM", "JAM", 388),
      "JPN": const Iso3166Entry("Japan", "JP", "JPN", 392),
      "JEY": const Iso3166Entry("Jersey", "JE", "JEY", 832),
      "JOR": const Iso3166Entry("Jordan", "JO", "JOR", 400),
      "KAZ": const Iso3166Entry("Kazakhstan", "KZ", "KAZ", 398),
      "KEN": const Iso3166Entry("Kenya", "KE", "KEN", 404),
      "KIR": const Iso3166Entry("Kiribati", "KI", "KIR", 296),
      "PRK": const Iso3166Entry(
          "Korea (the Democratic People's Republic of)", "KP", "PRK", 408),
      "KOR": const Iso3166Entry("Korea (the Republic of)", "KR", "KOR", 410),
      "KWT": const Iso3166Entry("Kuwait", "KW", "KWT", 414),
      "KGZ": const Iso3166Entry("Kyrgyzstan", "KG", "KGZ", 417),
      "LAO": const Iso3166Entry(
          "Lao People's Democratic Republic the", "LA", "LAO", 418),
      "LVA": const Iso3166Entry("Latvia", "LV", "LVA", 428),
      "LBN": const Iso3166Entry("Lebanon", "LB", "LBN", 0),
      "LSO": const Iso3166Entry("Lesotho", "LS", "LSO", 426),
      "LBR": const Iso3166Entry("Liberia", "LR", "LBR", 430),
      "LBY": const Iso3166Entry("Libya", "LY", "LBY", 434),
      "LIE": const Iso3166Entry("Liechtenstein", "LI", "LIE", 438),
      "LTU": const Iso3166Entry("Lithuania", "LT", "LTU", 440),
      "LUX": const Iso3166Entry("Luxembourg", "LU", "LUX", 442),
      "MAC": const Iso3166Entry("Macao", "MO", "MAC", 446),
      "MDG": const Iso3166Entry("Madagascar", "MG", "MDG", 450),
      "MWI": const Iso3166Entry("Malawi", "MW", "MWI", 454),
      "MYS": const Iso3166Entry("Malaysia", "MY", "MYS", 458),
      "MDV": const Iso3166Entry("Maldives", "MV", "MDV", 462),
      "MLI": const Iso3166Entry("Mali", "ML", "MLI", 466),
      "MLT": const Iso3166Entry("Malta", "MT", "MLT", 470),
      "MHL": const Iso3166Entry("Marshall Islands the", "MH", "MHL", 584),
      "MTQ": const Iso3166Entry("Martinique", "MQ", "MTQ", 474),
      "MRT": const Iso3166Entry("Mauritania", "MR", "MRT", 478),
      "MUS": const Iso3166Entry("Mauritius", "MU", "MUS", 480),
      "MYT": const Iso3166Entry("Mayotte", "YT", "MYT", 175),
      "MEX": const Iso3166Entry("Mexico", "MX", "MEX", 484),
      "FSM": const Iso3166Entry(
          "Micronesia (Federated States of)", "FM", "FSM", 583),
      "MDA": const Iso3166Entry("Moldova (the Republic of)", "MD", "MDA", 498),
      "MCO": const Iso3166Entry("Monaco", "MC", "MCO", 492),
      "MNG": const Iso3166Entry("Mongolia", "MN", "MNG", 496),
      "MNE": const Iso3166Entry("Montenegro", "ME", "MNE", 499),
      "MSR": const Iso3166Entry("Montserrat", "MS", "MSR", 0),
      "MAR": const Iso3166Entry("Morocco", "MA", "MAR", 504),
      "MOZ": const Iso3166Entry("Mozambique", "MZ", "MOZ", 508),
      "MMR": const Iso3166Entry("Myanmar", "MM", "MMR", 104),
      "NAM": const Iso3166Entry("Namibia", "NA", "NAM", 516),
      "NRU": const Iso3166Entry("Nauru", "NR", "NRU", 520),
      "NPL": const Iso3166Entry("Nepal", "NP", "NPL", 524),
      "NLD":
          const Iso3166Entry("Netherlands (Kingdom of the)", "NL", "NLD", 528),
      "NCL": const Iso3166Entry("New Caledonia", "NC", "NCL", 540),
      "NZL": const Iso3166Entry("New Zealand", "NZ", "NZL", 554),
      "NIC": const Iso3166Entry("Nicaragua", "NI", "NIC", 558),
      "NER": const Iso3166Entry("Niger the", "NE", "NER", 562),
      "NGA": const Iso3166Entry("Nigeria", "NG", "NGA", 566),
      "NIU": const Iso3166Entry("Niue", "NU", "NIU", 570),
      "NFK": const Iso3166Entry("Norfolk Island", "NF", "NFK", 574),
      "MKD": const Iso3166Entry("North Macedonia", "MK", "MKD", 807),
      "MNP":
          const Iso3166Entry("Northern Mariana Islands the", "MP", "MNP", 580),
      "NOR": const Iso3166Entry("Norway", "NO", "NOR", 578),
      "OMN": const Iso3166Entry("Oman", "OM", "OMN", 512),
      "PAK": const Iso3166Entry("Pakistan", "PK", "PAK", 586),
      "PLW": const Iso3166Entry("Palau", "PW", "PLW", 585),
      "PSE": const Iso3166Entry("Palestine, State of", "PS", "PSE", 275),
      "PAN": const Iso3166Entry("Panama", "PA", "PAN", 591),
      "PNG": const Iso3166Entry("Papua New Guinea", "PG", "PNG", 598),
      "PRY": const Iso3166Entry("Paraguay", "PY", "PRY", 600),
      "PER": const Iso3166Entry("Peru", "PE", "PER", 0),
      "PHL": const Iso3166Entry("Philippines the", "PH", "PHL", 608),
      "PCN": const Iso3166Entry("Pitcairn", "PN", "PCN", 612),
      "POL": const Iso3166Entry("Poland", "PL", "POL", 616),
      "PRT": const Iso3166Entry("Portugal", "PT", "PRT", 620),
      "PRI": const Iso3166Entry("Puerto Rico", "PR", "PRI", 630),
      "QAT": const Iso3166Entry("Qatar", "QA", "QAT", 634),
      "REU": const Iso3166Entry("Réunion", "RE", "REU", 638),
      "ROU": const Iso3166Entry("Romania", "RO", "ROU", 642),
      "RUS": const Iso3166Entry("Russian Federation the", "RU", "RUS", 643),
      "RWA": const Iso3166Entry("Rwanda", "RW", "RWA", 646),
      "BLM": const Iso3166Entry("Saint Barthélemy", "BL", "BLM", 652),
      "SHN": const Iso3166Entry(
          "Saint Helena, Ascension and Tristan da Cunha", "SH", "SHN", 654),
      "KNA": const Iso3166Entry("Saint Kitts and Nevis", "KN", "KNA", 659),
      "LCA": const Iso3166Entry("Saint Lucia", "LC", "LCA", 662),
      "MAF": const Iso3166Entry("Saint Martin (French part)", "MF", "MAF", 663),
      "SPM": const Iso3166Entry("Saint Pierre and Miquelon", "PM", "SPM", 666),
      "VCT": const Iso3166Entry(
          "Saint Vincent and the Grenadines", "VC", "VCT", 670),
      "WSM": const Iso3166Entry("Samoa", "WS", "WSM", 882),
      "SMR": const Iso3166Entry("San Marino", "SM", "SMR", 674),
      "STP": const Iso3166Entry("Sao Tome and Principe", "ST", "STP", 678),
      "SAU": const Iso3166Entry("Saudi Arabia", "SA", "SAU", 682),
      "SEN": const Iso3166Entry("Senegal", "SN", "SEN", 686),
      "SRB": const Iso3166Entry("Serbia", "RS", "SRB", 688),
      "SYC": const Iso3166Entry("Seychelles", "SC", "SYC", 690),
      "SLE": const Iso3166Entry("Sierra Leone", "SL", "SLE", 0),
      "SGP": const Iso3166Entry("Singapore", "SG", "SGP", 702),
      "SXM": const Iso3166Entry("Sint Maarten (Dutch part)", "SX", "SXM", 534),
      "SVK": const Iso3166Entry("Slovakia", "SK", "SVK", 703),
      "SVN": const Iso3166Entry("Slovenia", "SI", "SVN", 705),
      "SLB": const Iso3166Entry("Solomon Islands", "SB", "SLB", 90),
      "SOM": const Iso3166Entry("Somalia", "SO", "SOM", 706),
      "ZAF": const Iso3166Entry("South Africa", "ZA", "ZAF", 710),
      "SGS": const Iso3166Entry(
          "South Georgia and the South Sandwich Islands", "GS", "SGS", 239),
      "SSD": const Iso3166Entry("South Sudan", "SS", "SSD", 728),
      "ESP": const Iso3166Entry("Spain", "ES", "ESP", 724),
      "LKA": const Iso3166Entry("Sri Lanka", "LK", "LKA", 144),
      "SDN": const Iso3166Entry("Sudan the", "SD", "SDN", 729),
      "SUR": const Iso3166Entry("Suriname", "SR", "SUR", 740),
      "SJM": const Iso3166Entry("Svalbard and Jan Mayen", "SJ", "SJM", 744),
      "SWE": const Iso3166Entry("Sweden", "SE", "SWE", 752),
      "CHE": const Iso3166Entry("Switzerland", "CH", "CHE", 756),
      "SYR": const Iso3166Entry("Syrian Arab Republic the", "SY", "SYR", 760),
      "TWN": const Iso3166Entry("Taiwan (Province of China)", "TW", "TWN", 158),
      "TJK": const Iso3166Entry("Tajikistan", "TJ", "TJK", 762),
      "TZA": const Iso3166Entry(
          "Tanzania, the United Republic of", "TZ", "TZA", 834),
      "THA": const Iso3166Entry("Thailand", "TH", "THA", 764),
      "TLS": const Iso3166Entry("Timor-Leste", "TL", "TLS", 626),
      "TGO": const Iso3166Entry("Togo", "TG", "TGO", 768),
      "TKL": const Iso3166Entry("Tokelau", "TK", "TKL", 772),
      "TON": const Iso3166Entry("Tonga", "TO", "TON", 0),
      "TTO": const Iso3166Entry("Trinidad and Tobago", "TT", "TTO", 780),
      "TUN": const Iso3166Entry("Tunisia", "TN", "TUN", 788),
      "TUR": const Iso3166Entry("Türkiye", "TR", "TUR", 792),
      "TKM": const Iso3166Entry("Turkmenistan", "TM", "TKM", 795),
      "TCA":
          const Iso3166Entry("Turks and Caicos Islands the", "TC", "TCA", 796),
      "TUV": const Iso3166Entry("Tuvalu", "TV", "TUV", 798),
      "UGA": const Iso3166Entry("Uganda", "UG", "UGA", 800),
      "UKR": const Iso3166Entry("Ukraine", "UA", "UKR", 804),
      "ARE": const Iso3166Entry("United Arab Emirates the", "AE", "ARE", 784),
      "GBR": const Iso3166Entry(
          "United Kingdom of Great Britain and Northern Ireland the",
          "GB",
          "GBR",
          826),
      "UMI": const Iso3166Entry(
          "United States Minor Outlying Islands the", "UM", "UMI", 581),
      "USA":
          const Iso3166Entry("United States of America the", "US", "USA", 840),
      "URY": const Iso3166Entry("Uruguay", "UY", "URY", 858),
      "UZB": const Iso3166Entry("Uzbekistan", "UZ", "UZB", 860),
      "VUT": const Iso3166Entry("Vanuatu", "VU", "VUT", 548),
      "VEN": const Iso3166Entry(
          "Venezuela (Bolivarian Republic of)", "VE", "VEN", 862),
      "VNM": const Iso3166Entry("Viet Nam", "VN", "VNM", 704),
      "VGB": const Iso3166Entry("Virgin Islands (British)", "VG", "VGB", 92),
      "VIR": const Iso3166Entry("Virgin Islands (U.S.)", "VI", "VIR", 850),
      "WLF": const Iso3166Entry("Wallis and Futuna", "WF", "WLF", 876),
      "ESH": const Iso3166Entry("Western Sahara*", "EH", "ESH", 732),
      "YEM": const Iso3166Entry("Yemen", "YE", "YEM", 887),
      "ZMB": const Iso3166Entry("Zambia", "ZM", "ZMB", 894),
      "ZWE": const Iso3166Entry("Zimbabwe", "ZW", "ZWE", 716),
    };
  }

  String getAlpha2UsingAlpha3(String alpha3) {
    final entries = Iso3166Entry.getEntries();
    final entry = entries[alpha3];
    if (entry == null) {
      throw ArgumentError('Invalid alpha3 code: $alpha3');
    }
    return entry.alpha2;
  }

  int getNumericUsingAlpha3(String alpha3) {
    final entries = Iso3166Entry.getEntries();
    final entry = entries[alpha3];
    if (entry == null) {
      throw ArgumentError('Invalid alpha3 code: $alpha3');
    }
    return entry.numeric;
  }

  String getEnglishNameUsingAlpha3(String alpha3) {
    final entries = Iso3166Entry.getEntries();
    final entry = entries[alpha3];
    if (entry == null) {
      throw ArgumentError('Invalid alpha3 code: $alpha3');
    }
    return entry.englishName;
  }

}
